### ISSUE TITLE
npm start成功了，但是加载文件出错

### ISSUE THREAD

**Issue by asyalas** [Nealyang/React-Fullstack-Dianping-Demo#1]
![image](https://user-images.githubusercontent.com/25005604/31346177-cf8e83f6-ad4a-11e7-9c81-83ecb055f0fc.png)
npm 5.3.0
node v8.6.0

**Comment by Nealyang** [comment]
@asyalas 报错是资源文件没有加载到。查看下webpack配置文件，以及网页源码文件的访问地址是否正确
