### ISSUE TITLE
如果直接用async await,用saga还有意义么？

### ISSUE THREAD

**Issue by hstarorg** [Nealyang/React-Fullstack-Dianping-Demo#3]
一直没有想清楚用saga的意义，加上不喜欢生成器，所以一直抵触saga，还望解惑，谢谢~

**Comment by Nealyang** [comment]
redux的作用在于组织状态树，而这些状态树一般在应用中获取都是通过接口请求的。且不说saga，就说redux在于异步获取state的操作上，布局的麻烦度非常的大么？这也正是redux在异步处理上的一个鸡肋的问题。saga不用行不行？当然可以！我们有很多种方法来处理redux异步的。redux-thunk等等等。但是为什么会用，因为它方便清晰，能让代码非常的简介，分工非常的明确。用同步的方式处理异步。你抵触的不是生成器，而是一个新的方式和语法。克服这层学习的心理障碍，你会感受到saga带给你的方便之处。说一个技术有没有用，是当你用了以后才能够去评价的。

**Comment by hstarorg** [comment]
感谢回复。我推崇的是页面自治，也就是页面自己管理状态，并不需要去redux走一圈（出发点是页面之间并没有那么多的共享数据）。在这种思路下，我的redux是很薄的一层。至于我说不用saga，是考虑到既然是同步方式，我可以用async , await 来代替。在action中，直接同步写法呼叫reducer。其实有借鉴 `Vuex` 是思路，在这个里面，并不需要 `saga` 这样的东西，另外，在 `Angular` 中，更是直接抽取 `service` 来实现业务逻辑，同样也很少用全局state。

BTW: 尝试过用saga，但就我说之前说的，没感觉到有什么用。

**Comment by Nealyang** [comment]
对于你说的，redux很薄的一层，我想说redux推出来的观点就是，能不用则不用，咱不能为了用而去用，存在即合理，但是合理不代表绝对。阮一峰文章里又说道，"如果你不知道是否需要 Redux，那就是不需要它。"对于这个repository demo用到，的的确确是因为他是demo，为了练习而使用的，换句话说，这个基本用不到redux，不用，反而更简单。对于另一个repository website的demo，其实用redux还是有必要的。
什么时候需要用？
- 某个组件的状态，需要共享
- 某个状态需要在任何地方都可以拿到
- 一个组件需要改变全局状态
- 一个组件需要改变另一个组件的状态

OK，saga也好，生成器也罢，还是await种种，他只是手段，处理异步的一种手段。不觉得saga和await异曲同工之处很多么？所以我的观点就是，没有谁好谁坏，这些只是工具手段，总会有更加方便的来将其淘汰，作为coder，哪个方便，用哪个！

**Comment by hstarorg** [comment]
明白，感谢解惑。
我自己有一套完整的思路，就是刚说的。不过由于业界还有各种文档的用法，都是按照常规redux，chunk, saga这些玩意来搞，很少见有人分享大型系统架构的，所以想多多确认下。再次感谢~
